// <auto-generated />
using Lecture.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lecture.Migrations
{
    [DbContext(typeof(LectureDbContext))]
    partial class LectureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Lecture.Models.WriterModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("writers");
                });
#pragma warning restore 612, 618
        }
    }
}
